apiVersion: apps/v1
kind: Deployment

metadata:
  name: point-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: point-service
  template:
    metadata:
      labels:
        app: point-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: point-service
          image: 267837905230.dkr.ecr.ap-northeast-2.amazonaws.com/board-system/point-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: point-secret
                