services:
  user-service:
    container_name: user-service
    image: user-service
    ports: 
      - "8080:8080"
  board-service:
    container_name: board-service
    image: board-service
    ports:
      - "8081:8080"
    depends_on:
      cache-server:
        condition: service_healthy
  
  cache-server:
    container_name: cache-server
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
  point-service:
    container_name: point-service
    image: point-service
    ports:
      - "8082:8080"
  
  api-gateway-service:
    container_name: api-gateway-service
    image: api-gateway-service
    ports:
      - "8000:8080"
  
  kafka-server:
    image: apache/kafka:4.1.0
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: q1Sh-9_ISia_zwGINzRvyQ
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-server:9093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
      # KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS: kafka-server:9093
      # KAFKA_MAP_NETWORK_THREADS: 3
      # KAFKA_IO_THREADS: 8
      # KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: 1
      # KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      # KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      