services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  user-service:
    container_name: user-service
    image: ghcr.io/yunjeongwon/msa-user-service:latest
    ports: 
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/user_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-server:9092
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      mysql-db:
        condition: service_healthy

  board-service:
    container_name: board-service
    image: ghcr.io/yunjeongwon/msa-board-service:latest
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/board_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-server:9092
    depends_on:
      mysql-db:
        condition: service_healthy
      cache-server:
        condition: service_healthy
  
  cache-server:
    container_name: cache-server
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10

  point-service:
    container_name: point-service
    image: ghcr.io/yunjeongwon/msa-point-service:latest
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/point_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      mysql-db:
        condition: service_healthy

  api-gateway-service:
    container_name: api-gateway-service
    image: ghcr.io/yunjeongwon/msa-api-gateway-service:latest
    ports:
      - "8000:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}

  kafka-server:
    image: apache/kafka:4.1.0
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: q1Sh-9_ISia_zwGINzRvyQ
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-server:9093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
      # KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS: kafka-server:9093
      # KAFKA_MAP_NETWORK_THREADS: 3
      # KAFKA_IO_THREADS: 8
      # KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: 1
      # KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      # KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

volumes:
  mysql-data:
    name: board-system-mysql-data