apiVersion: v1
kind: ConfigMap

metadata:
  name: kafka-config

data:
  KAFKA_CLUSTER_ID: q1Sh-9_ISia_zwGINzRvyQ
  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-server:9093
  KAFKA_PROCESS_ROLES: broker,controller
  KAFKA_NODE_ID: 0
  KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
  KAFKA_LOG_DIRS: /var/lib/kafka/data
  KAFKA_NUM_PARTITIONS: 1
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  