apiVersion: apps/v1
kind: Deployment

metadata:
  name: board-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: board-service
  template:
    metadata:
      labels:
        app: board-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: board-service
          image: 267837905230.dkr.ecr.ap-northeast-2.amazonaws.com/board-system/board-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: board-config
            - secretRef:
                name: board-secret