apiVersion: apps/v1
kind: Deployment

metadata:
  name: board-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: board-service
  template:
    metadata:
      labels:
        app: board-service
    spec:
      containers:
        - name: board-service
          image: ghcr.io/yunjeongwon/msa-board-service:latest
          ports:
            - containerPorts: 8080
          envFrom:
            - configMapRef:
                name: board-config
            - secretRef:
                name: board-secret